# Анализ игровой индустрии

- Автор: Дегтярёва Александра Владимировна
- Дата: 09.11.2025

###  Цели и задачи проекта
Цель - Провести подробный анализ игровой индустрии для команды игры «Секреты Темнолесья»
1. Познакомиться с данными
2. Проверить данные на корректность
3. Провести предобработку (дубликаты, пропуски)

# Описание данных

- `Name` — название игры.
- `Platform` — название платформы.
- `Year of Release` — год выпуска игры.
- `Genre` — жанр игры.
- `NA sales` — продажи в Северной Америке (в миллионах проданных копий).
- `EU sales` — продажи в Европе (в миллионах проданных копий).
- `JP sales` — продажи в Японии (в миллионах проданных копий).
- `Other sales` — продажи в других странах (в миллионах проданных копий).
- `Critic Score` — оценка критиков (от 0 до 100).
- `User Score` — оценка пользователей (от 0 до 10).
- `Rating` — рейтинг организации ESRB (англ. Entertainment Software Rating Board).

### Содержимое проекта
1. Загрузка и знакомство с данными
2. Проверка ошибок в данных и их предобработка
3. Фильтрация данных
4. Категоризация данных
5. Вывод

##  Загрузка данных и знакомство с ними

- Загрузите необходимые библиотеки Python и данные датасета `/datasets/new_games.csv`.

In [1]:
# Импортируем библиотеку
import pandas as pd

In [2]:
df = pd.read_csv('/datasets/new_games.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16956 entries, 0 to 16955
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16954 non-null  object
 1   Platform         16956 non-null  object
 2   Year of Release  16681 non-null  float64
 3   Genre            16954 non-null  object
 4   NA sales         16956 non-null  float64
 5   EU sales         16956 non-null  object
 6   JP sales         16956 non-null  object
 7   Other sales      16956 non-null  float64
 8   Critic Score     8242 non-null   float64
 9   User Score       10152 non-null  object
 10  Rating           10085 non-null  object
dtypes: float64(4), object(7)
memory usage: 1.4+ MB

In [4]:
# Выводим первые строчки
df.head(11)

,Name,Platform,Year of Release,Genre,NA sales,EU sales,JP sales,Other sales,Critic Score,User Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
5,Tetris,GB,1989.0,Puzzle,23.20,2.26,4.22,0.58,NaN,NaN,NaN
6,New Super Mario Bros.,DS,2006.0,Platform,11.28,9.14,6.5,2.88,89.0,8.5,E
7,Wii Play,Wii,2006.0,Misc,13.96,9.18,2.93,2.84,58.0,6.6,E
8,New Super Mario Bros. Wii,Wii,2009.0,Platform,14.44,6.94,4.7,2.24,87.0,8.4,E
9,Duck Hunt,NES,1984.0,Shooter,26.93,0.63,0.28,0.47,NaN,NaN,NaN
10,Nintendogs,DS,2005.0,Simulation,9.05,10.95,1.93,2.74,NaN,NaN,NaN

In [5]:
# Выводим последние строчки 
df.tail(15)

,Name,Platform,Year of Release,Genre,NA sales,EU sales,JP sales,Other sales,Critic Score,User Score,Rating
16941,Mezase!! Tsuri Master DS,DS,2009.0,Sports,0.00,0.0,0.01,0.0,NaN,NaN,NaN
16942,Eiyuu Densetsu: Sora no Kiseki Material Collec...,PSP,2007.0,Role-Playing,0.00,0.0,0.01,0.0,NaN,NaN,NaN
16943,STORM: Frontline Nation,PC,2011.0,Strategy,0.00,0.01,0.0,0.0,60.0,7.2,E10+
16944,Strawberry Nauts,PSV,2016.0,Adventure,0.00,0.0,0.01,0.0,NaN,NaN,NaN
16945,Plushees,DS,2008.0,Simulation,0.01,0.0,0.0,0.0,NaN,tbd,E
16946,15 Days,PC,2009.0,Adventure,0.00,0.01,0.0,0.0,63.0,5.8,NaN
16947,Men in Black II: Alien Escape,GC,2003.0,Shooter,0.01,0.0,0.0,0.0,NaN,tbd,T
16948,Aiyoku no Eustia,PSV,2014.0,Misc,0.00,0.0,0.01,0.0,NaN,NaN,NaN
16949,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,0.01,0.0,0.0,0.0,NaN,NaN,NaN
16950,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,0.00,0.0,0.0,0.0,NaN,NaN,NaN
16951,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,0.00,0.0,0.01,0.0,NaN,NaN,NaN
16952,LMA Manager 2007,X360,2006.0,Sports,0.00,0.01,0.0,0.0,NaN,NaN,NaN
16953,Haitaka no Psychedelica,PSV,2016.0,Adventure,0.00,0.0,0.01,0.0,NaN,NaN,NaN
16954,Spirits & Spells,GBA,2003.0,Platform,0.01,0.0,0.0,0.0,NaN,NaN,NaN
16955,Winning Post 8 2016,PSV,2016.0,Simulation,0.00,0.0,0.01,0.0,NaN,NaN,NaN

In [6]:
# запоминаем кол-во строк
initial_rows = len(df)

- Сделайте вывод о полученных данных: данные какого объёма вам предоставили, соответствуют ли они описанию, встречаются ли в них пропуски, используются ли верные типы данных.
- Отметьте другие особенности данных, которые вы обнаружили и на которые стоит обратить внимание при предобработке. Например, вы можете проверить названия столбцов: все ли названия отражают содержимое данных и прописаны в удобном для работы виде.

###### Датасет содержит 11 столбцов и 16956 строк

Встречаются данные двух типов: 4 раза float64 и  7 раз object

 **Числовые значения с плавающей запятой (float64).** 
- `Year of Release`— содержит год выпуска игры, тип некорректный тк год всегда целое число, стоит поменять на **int16** 
- `NA sales` — хранит продажи в Северной Америке (в миллионах проданных копий), тип верный, но можно уменьшить разрядность до **float16**
- `Other sales` — содержит продажи в других странах (в миллионах проданных копий), тип верный но можно уменьшить разрядность до **float16**
- `Critic Score` — оценка критиков (от 0 до 100), содержит только целые значения, тип стоит поменять на **int8** (с учётом большого количесва пропусков)


**Строковые данные (object).** Восемь столбцов имеют тип данных `object`:
- `Name` — название игры, содержит стороковую информацию, верный тип данных 
- `Platform` — название платформы, можно поменять object на **category**
- `Genre` — жанр игры, можно поменять object на **category** 
- `EU sales` — продажи в Европе (в миллионах проданных копий), содержит числовую дробную информацию, надо поменять object на **float16**
- `JP sales` — продажи в Японии (в миллионах проданных копий), содержит числовую дробную информацию, надо поменять object на **float16**
- `User Score` — оценка пользователей (от 0 до 10), поменять на **float16**
- `Rating` — рейтинг организации ESRB (англ. Entertainment Software Rating Board), строковая информация, можно поменять object на **category**

**Пропуски содержатся в некоторых столбцах**

У `Name` и `Genre` пропуски это скорее всего случайные ошибки в данных, у `Year of Release` причина появления пропусков пока не особо ясна (вероятно дубликаты). `Critic Score` , `User Score` , `Rating` имеют пропуски из-за особенности сбора данных тк не каждый фильм имеет оценку

---

## Проверка ошибок в данных и их предобработка


###  Названия, или метки, столбцов датафрейма

- Выведите на экран названия всех столбцов датафрейма и проверьте их стиль написания.
- Приведите все столбцы к стилю snake case. Названия должны быть в нижнем регистре, а вместо пробелов — подчёркивания.

In [7]:
df.columns

Index(['Name', 'Platform', 'Year of Release', 'Genre', 'NA sales', 'EU sales',
       'JP sales', 'Other sales', 'Critic Score', 'User Score', 'Rating'],
      dtype='object')

In [8]:
# Приводим к нижнему регистру и убираем пробелы
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.columns

Index(['name', 'platform', 'year_of_release', 'genre', 'na_sales', 'eu_sales',
       'jp_sales', 'other_sales', 'critic_score', 'user_score', 'rating'],
      dtype='object')

### Типы данных

Встречаются данные двух типов: 4 раза float64 и  7 раз object

 **Числовые значения с плавающей запятой (float64).** 
- `year_of_release` содержит год выпуска игры, тип не корректный тк год всегда целое число, стоит поменять на **int16** 
- `na_sales` — хранит продажи в Северной Америке (в миллионах проданных копий), тип верный, но можно уменьшить разрядность до **float16**
- `other_sales` — содержит продажи в других странах (в миллионах проданных копий), тип верный но можно уменьшить разрядность до **float16**
- `critic_score` — оценка критиков (от 0 до 100), содержит только целые значения, тип стоит поменять на **int8** (с учётом большого количесва пропусков)


**Строковые данные (object).** Восемь столбцов имеют тип данных `object`:
- `name` — название игры, содержит стороковую информацию, верный тип данных 
- `platform` — название платформы, можно поменять object на **category**
- `genre` — жанр игры, можно поменять object на **category**
- `eu_sales` — продажи в Европе (в миллионах проданных копий), содержит числовую дробную информацию, надо поменять object на **float16**
- `jp_sales` — продажи в Японии (в миллионах проданных копий), содержит числовую дробную информацию, надо поменять object на **float16**
- `user_score` — оценка пользователей (от 0 до 10), поменять на **float16**
- `rating` — рейтинг организации ESRB (англ. Entertainment Software Rating Board), строковая информация, можно поменять object на **category**

In [9]:
# меняем тип данных с учетом пропусков и памяти
numeric_conversions = {
    'year_of_release': 'Int16',
    'critic_score': 'Int8', 
    'user_score': 'float16',
    'eu_sales': 'float16',
    'jp_sales': 'float16'
}

for column, dtype in numeric_conversions.items():
    df[column] = pd.to_numeric(df[column], errors='coerce').astype(dtype)

In [10]:
# изменение типа данных для оптимизации использования памяти
category_columns_float = ['na_sales','other_sales']
df[category_columns_float] = df[category_columns_float].astype('float16') 

category_columns_ctg = ['platform', 'genre']
df[category_columns_ctg] = df[category_columns_ctg].astype('category')

In [11]:
# проверяем 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16956 entries, 0 to 16955
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16954 non-null  object
 1   platform         16956 non-null  category
 2   year_of_release  16681 non-null  Int16
 3   genre            16954 non-null  category
 4   na_sales         16956 non-null  float16
 5   eu_sales         16950 non-null  float16
 6   jp_sales         16952 non-null  float16
 7   other_sales      16956 non-null  float16
 8   critic_score     8242 non-null   Int8
 9   user_score       7688 non-null   float16
 10  rating           10085 non-null  object
dtypes: Int16(1), Int8(1), category(2), float16(5), object(2)
memory usage: 548.6+ KB

### Наличие пропусков в данных

- Посчитайте количество пропусков в каждом столбце в абсолютных и относительных значениях.

In [12]:
# выводим количество пропущенных строк в датафрейме
df.isna().sum()

name                  2
platform              0
year_of_release     275
genre                 2
na_sales              0
eu_sales              6
jp_sales              4
other_sales           0
critic_score       8714
user_score         9268
rating             6871
dtype: int64

In [13]:
# подсчитываем процент строк с пропусками
df.isna().sum() / len(df) * 100

name                0.011795
platform            0.000000
year_of_release     1.621845
genre               0.011795
na_sales            0.000000
eu_sales            0.035386
jp_sales            0.023590
other_sales         0.000000
critic_score       51.391838
user_score         54.659118
rating             40.522529
dtype: float64

**Пропуски содержат:**
- `name` - всего 2 значения, очень маленький процент, можно удалить или оставить как есть
- `year_of_release` (пропуски в виде NaN) 275 пропусков, почти 2%  маленькое количество пропусков, оставить как/заменить на ноль/удалить
- `genre` тоже всего 2 пропуска, оставить как есть или удалить
- `eu_sales` и `jp_sales` маленькое количество пропусков, можно заменить средним
- `critic_score` и `user_score` (пропуски в виде NaN) больше половины данных - пропуски, заменить на значение-индикатор
- `rating` тоже много пропусков (40%) можно заполнить в зависимости от кол-ва продаж

У `name` и `genre` пропуски это скорее всего случайные ошибки в данных, у `year_of_release` причина появления пропусков пока не особо ясна (вероятно дубликаты или ошибки сбора данных). `critic_score` , `user_score` , `rating` имеют пропуски из-за особенности сбора данных тк не каждый фильм имеет оценку, например, в силу года. У слишком старых фильмов не скорее всего не будет оценок.

In [14]:
# удаляем строки с маленьким % пропусков 

df = df[~df['name'].isna()]
df = df[~df['genre'].isna()]
df = df[~df['eu_sales'].isna()]
df = df[~df['jp_sales'].isna()]
df = df[~df['year_of_release'].isna()]

# заменяем пустые значения в critic_score и user_score индикатором -1
df['critic_score'] =df['critic_score'].fillna(-1)
df['user_score'] =df['user_score'].fillna(-1)

# (рейтинг в данном случае не может быть нулевым, нулём обозначаем пропуск)
df['rating'] =df['rating'].fillna(0)

# меняем тип у rating
df['rating'] = df['rating'].astype('category')

In [15]:
# проверяем результат обработки пропусков
df.isna().sum()

name               0
platform           0
year_of_release    0
genre              0
na_sales           0
eu_sales           0
jp_sales           0
other_sales        0
critic_score       0
user_score         0
rating             0
dtype: int64

### Явные и неявные дубликаты в данных

In [16]:
df.describe()

,year_of_release,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score
count,16669.000000,16669.000000,16669.000000,16669.000000,16669.000000,16669.000000,16669.000000
mean,2006.486592,0.262207,0.144897,0.077881,0.047272,32.892375,2.679688
std,5.872946,0.813477,0.503418,0.309082,0.186890,36.276004,4.167969
min,1980.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000
50%,2007.000000,0.080017,0.020004,0.000000,0.010002,-1.000000,-1.000000
75%,2010.000000,0.239990,0.109985,0.040009,0.029999,70.000000,7.300781
max,2016.000000,41.375000,28.953125,10.218750,10.570312,98.000000,9.703125

In [17]:
# количество уникальных значений (unique), самое частое значение (top) частотa (freq)
df.describe(include='object')

# 12 повторений одного названия говорит о дубликатах

                               name
count                         16669
unique                        11422
top     Need for Speed: Most Wanted
freq                             12

In [18]:
# количество уникальных значений для каждого столбца
print("Кол-во уникальных значений по столбцам:")
print(df.nunique().sort_values())

print("Кол-во столбцов:",len(df))
# кол-во уникальных значений говорит о наличии дубликатов

Кол-во уникальных значений по столбцам:
rating                 9
genre                 24
platform              31
year_of_release       37
critic_score          82
user_score            96
other_sales          155
jp_sales             244
eu_sales             307
na_sales             401
name               11422
dtype: int64
Кол-во столбцов: 16669

In [36]:
# смотрим на наличие неявнях дубликатов
for column in ['platform','year_of_release','genre','rating']:
    print(f'Уникальные значения в столбце {column}:')
    print(df[column].sort_values().unique())
    print()
    
# видим дубликаты из-за верхнего регистра у genre

# у platform, year_of_release и rating дубликатов нет

Уникальные значения в столбце platform:
['2600', '3DO', '3DS', 'DC', 'DS', ..., 'Wii', 'WiiU', 'X360', 'XB', 'XOne']
Length: 31
Categories (31, object): ['2600', '3DO', '3DS', 'DC', ..., 'WiiU', 'X360', 'XB', 'XOne']

Уникальные значения в столбце year_of_release:
<IntegerArray>
[1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]
Length: 37, dtype: Int16

Уникальные значения в столбце genre:
['action', 'adventure', 'fighting', 'misc', 'platform', ..., 'role-playing', 'shooter', 'simulation', 'sports', 'strategy']
Length: 12
Categories (12, object): ['action', 'adventure', 'fighting', 'misc', ..., 'shooter', 'simulation', 'sports', 'strategy']

Уникальные значения в столбце rating:
[0, 'AO', 'E', 'E10+', 'EC', 'K-A', 'M', 'RP', 'T']
Categories (9, object): [0, 'AO', 'E', 'E10+', ..., 'K-A', 'M', 'RP', 'T']

In [21]:
# приводим всё к одному регистру 
df['genre'] = df['genre'].str.lower()
unique_count = df['genre'].unique()
print(unique_count)

df['name'] = df['name'].str.lower()

# меняем тип данных обратно на категорию
df['genre'] = df['genre'].astype('category')

# меняем тип на category
df['platform'] = df['platform'].astype('category')

['sports' 'platform' 'racing' 'role-playing' 'puzzle' 'misc' 'shooter'
 'simulation' 'action' 'fighting' 'adventure' 'strategy']

Неявные дубликаты устранены, приступаем к явным

In [22]:
# выявляем явные дубликаты по всему df
df.duplicated().sum() 
df.nunique().sort_values()

rating                 9
genre                 12
platform              31
year_of_release       37
critic_score          82
user_score            96
other_sales          155
jp_sales             244
eu_sales             307
na_sales             401
name               11422
dtype: int64

In [23]:
# выявляем явные дубликаты по столбцу name
df.duplicated('name').sum()

5247

In [24]:
# удаляем явные дубликаты по name и создаём новый df
df_cleaned = df.drop_duplicates(subset='name', keep='first', inplace=False) 
df_cleaned.nunique().sort_values()

rating                 8
genre                 12
platform              31
year_of_release       37
critic_score          80
user_score            93
other_sales          146
jp_sales             242
eu_sales             287
na_sales             383
name               11422
dtype: int64

In [25]:
# удаляем полные дубликаты 
df_cleaned_all = df.drop_duplicates(subset=['name','platform','genre','year_of_release','na_sales','eu_sales','jp_sales','other_sales','critic_score','user_score','rating'], keep='first', inplace=False) 
df_cleaned_all.nunique().sort_values()

rating                 9
genre                 12
platform              31
year_of_release       37
critic_score          82
user_score            96
other_sales          155
jp_sales             244
eu_sales             307
na_sales             401
name               11422
dtype: int64

In [26]:
# считаем количество удалённых строк в абсолютных и относительных значениях 
cleaned_rows = len(df_cleaned_all)
deleted_rows_absolute = initial_rows - cleaned_rows
deleted_rows_relative = (deleted_rows_absolute / initial_rows) * 100

print("Результаты очистки данных:")
print(f"Исходное количество строк: {initial_rows}")
print(f"Количество строк после очистки: {cleaned_rows}")
print(f"Удалено строк (абсолютное значение): {deleted_rows_absolute}")
print(f"Удалено строк (относительное значение): {deleted_rows_relative:.2f}%")

Результаты очистки данных:
Исходное количество строк: 16956
Количество строк после очистки: 16434
Удалено строк (абсолютное значение): 522
Удалено строк (относительное значение): 3.08%

Промежуточные выводы

1. Были устранены неявные дубликаты в genre с помощью lower() тк изначально рагистр у данных не совпадал
2. Поработали с явными дубликатами в name тк название игры не может повторяться
3. Удалили полностью совпадающие строчки 
4. Общее количество данных уменьшилось на 3%

---

##  Фильтрация данных

Коллеги хотят изучить историю продаж игр в начале XXI века, и их интересует период с 2000 по 2013 год включительно. Отберите данные по этому показателю. Сохраните новый срез данных в отдельном датафрейме, например `df_actual`.

In [27]:
#  фильтруем значения
df_actual = df_cleaned_all.query('2000 <= year_of_release <= 2013').copy()

In [28]:
# проверяем
unique_count = df_actual['year_of_release'].unique()
print(unique_count)

<IntegerArray>
[2006, 2008, 2009, 2005, 2007, 2010, 2013, 2004, 2002, 2001, 2011, 2012, 2003,
 2000]
Length: 14, dtype: Int16

In [29]:
# смотрим информацию по финальным данным
df_actual.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12772 entries, 0 to 16954
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             12772 non-null  object
 1   platform         12772 non-null  category
 2   year_of_release  12772 non-null  Int16
 3   genre            12772 non-null  category
 4   na_sales         12772 non-null  float16
 5   eu_sales         12772 non-null  float16
 6   jp_sales         12772 non-null  float16
 7   other_sales      12772 non-null  float16
 8   critic_score     12772 non-null  Int8
 9   user_score       12772 non-null  float16
 10  rating           12772 non-null  category
dtypes: Int16(1), Int8(1), category(3), float16(5), object(1)
memory usage: 426.1+ KB

In [30]:
df_actual.head()

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,wii sports,Wii,2006,sports,41.375000,28.953125,3.769531,8.453125,76,8.000000,E
2,mario kart wii,Wii,2008,racing,15.679688,12.757812,3.789062,3.289062,82,8.296875,E
3,wii sports resort,Wii,2009,sports,15.609375,10.929688,3.279297,2.949219,80,8.000000,E
6,new super mario bros.,DS,2006,platform,11.281250,9.140625,6.500000,2.880859,89,8.500000,E
7,wii play,Wii,2006,misc,13.960938,9.179688,2.929688,2.839844,58,6.601562,E

---

##  Категоризация данных
    
Проведите категоризацию данных:
- Разделите все игры по оценкам пользователей и выделите такие категории: высокая оценка (от 8 до 10 включительно), средняя оценка (от 3 до 8, не включая правую границу интервала) и низкая оценка (от 0 до 3, не включая правую границу интервала).

In [31]:
df_actual['user_score_level'] = pd.cut(df_actual['user_score'], bins=[0, 3, 8, 11], labels=["low", "medium", "high"],right=False)

- Разделите все игры по оценкам критиков и выделите такие категории: высокая оценка (от 80 до 100 включительно), средняя оценка (от 30 до 80, не включая правую границу интервала) и низкая оценка (от 0 до 30, не включая правую границу интервала).

In [32]:
df_actual['critic_score_level'] = pd.cut(df_actual['critic_score'], bins=[0, 30, 80, 101], labels=["low", "medium", "high"],right=False)

In [33]:
# проверяем 
df_actual.head(4)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,user_score_level,critic_score_level
0,wii sports,Wii,2006,sports,41.375000,28.953125,3.769531,8.453125,76,8.000000,E,high,medium
2,mario kart wii,Wii,2008,racing,15.679688,12.757812,3.789062,3.289062,82,8.296875,E,high,high
3,wii sports resort,Wii,2009,sports,15.609375,10.929688,3.279297,2.949219,80,8.000000,E,high,high
6,new super mario bros.,DS,2006,platform,11.281250,9.140625,6.500000,2.880859,89,8.500000,E,high,high

- После категоризации данных проверьте результат: сгруппируйте данные по выделенным категориям и посчитайте количество игр в каждой категории.

In [34]:
df_actual.groupby(['user_score_level','critic_score_level'])['name'].count()

user_score_level  critic_score_level
low               low                     17
                  medium                  77
                  high                     1
medium            low                     30
                  medium                3157
                  high                   638
high              low                      1
                  medium                1166
                  high                  1014
Name: name, dtype: int64

- Выделите топ-7 платформ по количеству игр, выпущенных за весь актуальный период.

In [35]:
# Группируем по платформе, считаем количество игр и сортируем по убыванию
platform_games = df_actual.groupby('platform')['name'].count().sort_values(ascending=False)

# Выводим первые 7 платформ
platform_games.head(7)

platform
PS2     2126
DS      2117
Wii     1275
PSP     1179
X360    1118
PS3     1087
GBA      810
Name: name, dtype: int64

---

## Итоговый вывод

В конце напишите основной вывод и отразите, какую работу проделали. Не забудьте указать описание среза данных и новых полей, которые добавили в исходный датасет.

#### Общие выводы
Данные демонстрируют высокую концентрацию игровой индустрии вокруг ограниченного числа платформ, что свидетельствует о:

- Наличии доминирующих платформ, которые привлекают наибольшее внимание разработчиков

- Стратегическом фокусе издателей на наиболее перспективных и популярных платформах

Первые 2-3 позиции в рейтинге занимают платформы с наибольшей пользовательской базой и лучшими коммерческими показателями, что делает их наиболее привлекательными для разработчиков и издателей.

Наблюдается явная связь между пользовательскими оценками и оценками критиков. Игры, получившие высокие оценки от пользователей, также высоко оцениваются профессиональными критиками. Подавляющее большинство игр получают средние оценки как от пользователей, так и от критиков, что свидетельствует о стандартизации качества в индустрии.

#### Комментарии о проделанной работе 
Были выполнены следующие задачи:
- загрузка и первичный анализ данных 
- предобработка и очистка данных (удаление дуюликатов, заполнение пропусков)
- фильтрация данных (за релевантный отрезок `2000 - 2013`)
- категоризация и анализ данных (добавлены новые столбы `user_score_level` и `critic_score_level`)
- формулировка выводов